export enum AdminAuditAction {
  ADMIN_LOGIN = 'admin.login',
  ADMIN_LOGOUT = 'admin.logout',
  USER_STATUS_UPDATE = 'user.status.update',
  USER_ROLE_UPDATE = 'user.role.update',
  COMPANY_VERIFICATION_UPDATE = 'company.verification.update',
  JOB_MODERATION_UPDATE = 'job.moderation.update',
  WALLET_ADJUST = 'wallet.adjust',
  WALLET_TRANSACTIONS_VIEW = 'wallet.transactions.view',
  USER_WALLET_VIEW = 'user.wallet.view',
  USER_TOPUP_ORDERS_VIEW = 'user.topup_orders.view',
  SEPAY_CONFIG_VIEW = 'sepay.config.view',
  SEPAY_CONFIG_UPDATE = 'sepay.config.update',
  SEPAY_SECRET_ROTATE = 'sepay.secret.rotate',
  SEPAY_CONNECTION_TEST = 'sepay.test_connection',
  SEPAY_DIAGNOSTICS_VIEW = 'sepay.diagnostics.view',
  RAG_CHAT_CONFIG_VIEW = 'rag_chat.config.view',
  RAG_CHAT_CONFIG_UPDATE = 'rag_chat.config.update',
  RAG_CHAT_SECRET_ROTATE = 'rag_chat.secret.rotate',
  RAG_CHAT_HEALTH_VIEW = 'rag_chat.health.view',
  RAG_CHAT_CONNECTION_TEST = 'rag_chat.test_connection',
  JOB_PROMOTION_VIEW = 'job_promotion.view',
  JOB_PROMOTION_CREATE = 'job_promotion.create',
  JOB_PROMOTION_UPDATE = 'job_promotion.update',
  JOB_PROMOTION_DELETE = 'job_promotion.delete',
  JOB_PROMOTION_PLAN_CREATE = 'job_promotion_plan.create',
  JOB_PROMOTION_PLAN_UPDATE = 'job_promotion_plan.update',
  JOB_PROMOTION_PLAN_DELETE = 'job_promotion_plan.delete'
}

export enum AdminAuditTargetType {
  ADMIN = 'admin',
  USER = 'user',
  COMPANY = 'company',
  JOB = 'job',
  WALLET = 'wallet',
  WALLET_TRANSACTION = 'wallet_transaction',
  WALLET_TOPUP_ORDER = 'wallet_topup_order',
  SEPAY = 'sepay',
  RAG_CHAT = 'rag_chat',
  SYSTEM_SETTING = 'system_setting',
  JOB_PROMOTION = 'job_promotion',
  JOB_PROMOTION_PLAN = 'job_promotion_plan'
}